# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(blank=True, max_length=1024, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'in_db': 'local_crate',
            },
        ),
    ]
