# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 20:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'in_db': 'crate',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(blank=True, max_length=1024, primary_key=True, serialize=False)),
                ('author_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('published', models.DateTimeField(default=datetime.datetime.now)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'in_db': 'crate',
            },
        ),
    ]
